/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kj.crazyconnectfour.frames;

import kj.crazyconnectfour.enums.TokenColor;
import kj.crazyconnectfour.models.GameBoard;
import kj.crazyconnectfour.models.Scoreboard;
import kj.crazyconnectfour.models.SuperToken;

/**
 *
 * @author Kera
 */
public class GamePlay extends javax.swing.JFrame {

    private GameBoard newGameBoard = new GameBoard();
    private Scoreboard newScoreBoard = new Scoreboard();
    /**
     * Creates new form GamePlay
     */
    public GamePlay() {
        for(int i=0;i<6;i++)
        {
            column1[i] = new javax.swing.JLabel();
            column2[i] = new javax.swing.JLabel();
            column3[i] = new javax.swing.JLabel();
            column4[i] = new javax.swing.JLabel();
            column5[i] = new javax.swing.JLabel();
            column6[i] = new javax.swing.JLabel();
        }
        
        initComponents();
 
        for(int i=5;i>=0;i--)
        {
            columnOnePanel.add(column1[i]);
            columnTwoPanel.add(column2[i]);
            columnThreePanel.add(column3[i]);
            columnFourPanel.add(column4[i]);
            columnFivePanel.add(column5[i]);
            columnSixPanel.add(column6[i]);
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpMenuItems = new javax.swing.JPanel();
        menuPlayerStatsButton = new javax.swing.JButton();
        menuHelpButton = new javax.swing.JButton();
        menuExitButton = new javax.swing.JButton();
        jlTitle = new javax.swing.JLabel();
        gameBoardPanel = new javax.swing.JPanel();
        columnOnePanel = new javax.swing.JPanel();
        columnTwoPanel = new javax.swing.JPanel();
        columnThreePanel = new javax.swing.JPanel();
        columnFourPanel = new javax.swing.JPanel();
        columnFivePanel = new javax.swing.JPanel();
        columnSixPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtPlayerText = new javax.swing.JTextField();
        playerScore = new javax.swing.JTextField();
        jtComputerText = new javax.swing.JTextField();
        computerScore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBody.setBackground(new java.awt.Color(204, 255, 204));
        jpBody.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jpMenuItems.setBackground(new java.awt.Color(204, 204, 255));
        jpMenuItems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuPlayerStatsButton.setFont(new java.awt.Font("HanziPen SC", 1, 18)); // NOI18N
        menuPlayerStatsButton.setText("Player Stats");
        menuPlayerStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlayerStatsButtonActionPerformed(evt);
            }
        });

        menuHelpButton.setFont(new java.awt.Font("HanziPen SC", 1, 18)); // NOI18N
        menuHelpButton.setText("Help");
        menuHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpButtonActionPerformed(evt);
            }
        });

        menuExitButton.setFont(new java.awt.Font("HanziPen SC", 1, 18)); // NOI18N
        menuExitButton.setText("Exit");
        menuExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuItemsLayout = new javax.swing.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPlayerStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuItemsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(menuPlayerStatsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuHelpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuExitButton)
                .addGap(29, 29, 29))
        );

        jlTitle.setFont(new java.awt.Font("HanziPen SC", 1, 36)); // NOI18N
        jlTitle.setForeground(new java.awt.Color(153, 153, 255));
        jlTitle.setText("Crazy Connect Four");

        gameBoardPanel.setBackground(new java.awt.Color(255, 255, 255));
        gameBoardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gameBoardPanel.setLayout(new java.awt.GridLayout(1, 5));

        columnOnePanel.setBackground(new java.awt.Color(255, 255, 255));
        columnOnePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnOnePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnOnePanelMouseClicked(evt);
            }
        });
        columnOnePanel.setLayout(new javax.swing.BoxLayout(columnOnePanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnOnePanel);

        columnTwoPanel.setBackground(new java.awt.Color(255, 255, 255));
        columnTwoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnTwoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnTwoPanelMouseClicked(evt);
            }
        });
        columnTwoPanel.setLayout(new javax.swing.BoxLayout(columnTwoPanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnTwoPanel);

        columnThreePanel.setBackground(new java.awt.Color(255, 255, 255));
        columnThreePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnThreePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnThreePanelMouseClicked(evt);
            }
        });
        columnThreePanel.setLayout(new javax.swing.BoxLayout(columnThreePanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnThreePanel);

        columnFourPanel.setBackground(new java.awt.Color(255, 255, 255));
        columnFourPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnFourPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnFourPanelMouseClicked(evt);
            }
        });
        columnFourPanel.setLayout(new javax.swing.BoxLayout(columnFourPanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnFourPanel);

        columnFivePanel.setBackground(new java.awt.Color(255, 255, 255));
        columnFivePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnFivePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnFivePanelMouseClicked(evt);
            }
        });
        columnFivePanel.setLayout(new javax.swing.BoxLayout(columnFivePanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnFivePanel);

        columnSixPanel.setBackground(new java.awt.Color(255, 255, 255));
        columnSixPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        columnSixPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                columnSixPanelMouseClicked(evt);
            }
        });
        columnSixPanel.setLayout(new javax.swing.BoxLayout(columnSixPanel, javax.swing.BoxLayout.PAGE_AXIS));
        gameBoardPanel.add(columnSixPanel);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jtPlayerText.setBackground(new java.awt.Color(204, 255, 204));
        jtPlayerText.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtPlayerText.setText("Player Score");
        jtPlayerText.setBorder(null);

        jtComputerText.setBackground(new java.awt.Color(204, 255, 204));
        jtComputerText.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtComputerText.setText("Computer Score");
        jtComputerText.setBorder(null);

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(23, 131, Short.MAX_VALUE)
                        .addComponent(jlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                                        .addComponent(jtPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))
                                    .addComponent(playerScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtComputerText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(computerScore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(gameBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitle)
                .addGap(18, 18, 18)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(jpMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtComputerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(computerScore))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addComponent(gameBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPlayerStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlayerStatsButtonActionPerformed
          PlayerStats score = new PlayerStats();
          score.setVisible(true);
    }//GEN-LAST:event_menuPlayerStatsButtonActionPerformed

    private void menuHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpButtonActionPerformed
           HelpFrame help = new HelpFrame();
           help.setVisible(true);
    }//GEN-LAST:event_menuHelpButtonActionPerformed

    private void menuExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuExitButtonActionPerformed

    private void columnOnePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnOnePanelMouseClicked
        playToken(1);
    }//GEN-LAST:event_columnOnePanelMouseClicked

    private void columnTwoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnTwoPanelMouseClicked
        playToken(2);
    }//GEN-LAST:event_columnTwoPanelMouseClicked

    private void columnThreePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnThreePanelMouseClicked
        playToken(3);
    }//GEN-LAST:event_columnThreePanelMouseClicked

    private void columnFourPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnFourPanelMouseClicked
        playToken(4);
    }//GEN-LAST:event_columnFourPanelMouseClicked

    private void columnFivePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnFivePanelMouseClicked
        playToken(5);
    }//GEN-LAST:event_columnFivePanelMouseClicked

    private void columnSixPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_columnSixPanelMouseClicked
        playToken(6);
    }//GEN-LAST:event_columnSixPanelMouseClicked

    private void playToken(int column) {
        int result = this.newGameBoard.playTokenInColumn(String.valueOf(column));//prompt where they should play token
        updateTokenGrid();
        
       if (result == 1) { //player won
            //display tokens in GUI
            updateTokenGrid();
            
            this.newScoreBoard.calculateWinnerScore(0);//display scoreboard
            updateScoreboard();
            newGameBoard = new GameBoard(); //reset gameboard
           // break;
        }

        result = this.newGameBoard.computerPlay();
    
        if (result == 2){ //computer won
            updateTokenGrid();
            this.newScoreBoard.calculateWinnerScore(1);//display scoreboard
            updateScoreboard();
            newGameBoard = new GameBoard(); //reset gameboard
           // break;
        }
    }
    
    private void updateScoreboard() {
        playerScore.setText(String.valueOf(Scoreboard.getNumberPlayerWins()));
        computerScore.setText(String.valueOf(Scoreboard.getNumberComputerWins()));
    }
    
    private void updateTokenGrid() {
        SuperToken[][] tokenGrid = newGameBoard.getTokenGrid();
        
        for(int i=0; i<tokenGrid.length;i++) {
            for (int j=0;j<tokenGrid[i].length;j++){
                SuperToken token = tokenGrid[i][j];
                
                if(token == null)
                {
                    if(j == 0)
                    {
                        column1[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                    if(j == 1)
                    {
                        column2[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                    if(j == 2)
                    {
                        column3[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                    if(j == 3)
                    {
                        column4[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                    if(j == 4)
                    {
                        column5[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                    if(j == 5)
                    {
                        column6[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/White_Token.png")));
                    }
                }
                else
                {
                    TokenColor color = token.getTokenColor();
                    if(color == TokenColor.RED) {
                        if(j == 0)
                        {
                            column1[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                        if(j == 1)
                        {
                            column2[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                        if(j == 2)
                        {
                            column3[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                        if(j == 3)
                        {
                            column4[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                        if(j == 4)
                        {
                            column5[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                        if(j == 5)
                        {
                            column6[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Red_Token.png")));
                        }
                    }
                    else if(color == TokenColor.BLUE) {
                        if(j == 0)
                        {
                            column1[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                        if(j == 1)
                        {
                            column2[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                        if(j == 2)
                        {
                            column3[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                        if(j == 3)
                        {
                            column4[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                        if(j == 4)
                        {
                            column5[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                        if(j == 5)
                        {
                            column6[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/kj/crazyconnectfour/images/Blue_Token.png")));
                        }
                
                    }
                }
            }
        }
    }
        
  
    
    javax.swing.JLabel[] column1 = new javax.swing.JLabel[6];
    javax.swing.JLabel[] column2 = new javax.swing.JLabel[6];
    javax.swing.JLabel[] column3 = new javax.swing.JLabel[6];
    javax.swing.JLabel[] column4 = new javax.swing.JLabel[6];
    javax.swing.JLabel[] column5 = new javax.swing.JLabel[6];
    javax.swing.JLabel[] column6 = new javax.swing.JLabel[6];
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel columnFivePanel;
    private javax.swing.JPanel columnFourPanel;
    private javax.swing.JPanel columnOnePanel;
    private javax.swing.JPanel columnSixPanel;
    private javax.swing.JPanel columnThreePanel;
    private javax.swing.JPanel columnTwoPanel;
    private javax.swing.JTextField computerScore;
    private javax.swing.JPanel gameBoardPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JTextField jtComputerText;
    private javax.swing.JTextField jtPlayerText;
    private javax.swing.JButton menuExitButton;
    private javax.swing.JButton menuHelpButton;
    private javax.swing.JButton menuPlayerStatsButton;
    private javax.swing.JTextField playerScore;
    // End of variables declaration//GEN-END:variables
}
