/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kj.crazyconnectfour.frames;

import java.text.DecimalFormat;
import kj.crazyconnectfour.models.GameBoard;
import kj.crazyconnectfour.models.Scoreboard;

/**
 *
 * @author Kera
 */
public class PlayerStats extends javax.swing.JFrame {

    /**
     * Creates new form PlayerStats
     */
    public PlayerStats() {
        initComponents();
        jtPlayerText.setText(GameBoard.getPlayer().getName() + "'s Score");
        playerScore.setText(String.valueOf(Scoreboard.getNumberPlayerWins()));
        computerScore.setText(String.valueOf(Scoreboard.getNumberComputerWins()));
        DecimalFormat myFormatter = new DecimalFormat("###.##");
        String output = myFormatter.format(Scoreboard.getPercentageWins());
        jPercentageWon.setText(output);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpPlayerTitle = new javax.swing.JPanel();
        jlPlayerTitle = new javax.swing.JLabel();
        jtPlayerText = new javax.swing.JTextField();
        playerScore = new javax.swing.JTextField();
        jtComputerText = new javax.swing.JTextField();
        computerScore = new javax.swing.JTextField();
        playerContinueButton = new javax.swing.JButton();
        jtPlayerText2 = new javax.swing.JTextField();
        jPercentageWon = new javax.swing.JTextField();
        jtPlayerText3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jpPlayerTitle.setBackground(new java.awt.Color(204, 255, 204));

        jlPlayerTitle.setFont(new java.awt.Font("HanziPen SC", 1, 18)); // NOI18N
        jlPlayerTitle.setForeground(new java.awt.Color(102, 102, 255));
        jlPlayerTitle.setText("Player Statistics");

        javax.swing.GroupLayout jpPlayerTitleLayout = new javax.swing.GroupLayout(jpPlayerTitle);
        jpPlayerTitle.setLayout(jpPlayerTitleLayout);
        jpPlayerTitleLayout.setHorizontalGroup(
            jpPlayerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPlayerTitleLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jlPlayerTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPlayerTitleLayout.setVerticalGroup(
            jpPlayerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlayerTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlPlayerTitle)
                .addContainerGap())
        );

        jtPlayerText.setBackground(new java.awt.Color(204, 255, 204));
        jtPlayerText.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtPlayerText.setText("Player Score");
        jtPlayerText.setBorder(null);
        jtPlayerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPlayerTextActionPerformed(evt);
            }
        });

        playerScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerScoreActionPerformed(evt);
            }
        });

        jtComputerText.setBackground(new java.awt.Color(204, 255, 204));
        jtComputerText.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtComputerText.setText("Computer Score");
        jtComputerText.setBorder(null);
        jtComputerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComputerTextActionPerformed(evt);
            }
        });

        computerScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerScoreActionPerformed(evt);
            }
        });

        playerContinueButton.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        playerContinueButton.setText("Continue");
        playerContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerContinueButtonActionPerformed(evt);
            }
        });

        jtPlayerText2.setBackground(new java.awt.Color(204, 255, 204));
        jtPlayerText2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtPlayerText2.setText("You have won ");
        jtPlayerText2.setBorder(null);
        jtPlayerText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPlayerText2ActionPerformed(evt);
            }
        });

        jtPlayerText3.setBackground(new java.awt.Color(204, 255, 204));
        jtPlayerText3.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jtPlayerText3.setText("% of the games.");
        jtPlayerText3.setBorder(null);
        jtPlayerText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPlayerText3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPlayerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jtPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(computerScore)
                            .addComponent(jtComputerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtPlayerText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerContinueButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPercentageWon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtPlayerText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpPlayerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(playerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtComputerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPlayerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(computerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPlayerText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPercentageWon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPlayerText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(playerContinueButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPlayerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPlayerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPlayerTextActionPerformed

    private void playerScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerScoreActionPerformed

    }//GEN-LAST:event_playerScoreActionPerformed

    private void jtComputerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComputerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtComputerTextActionPerformed

    private void computerScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerScoreActionPerformed

    private void jtPlayerText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPlayerText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPlayerText2ActionPerformed

    private void jtPlayerText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPlayerText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPlayerText3ActionPerformed

    private void playerContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerContinueButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_playerContinueButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField computerScore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPercentageWon;
    private javax.swing.JLabel jlPlayerTitle;
    private javax.swing.JPanel jpPlayerTitle;
    private javax.swing.JTextField jtComputerText;
    private javax.swing.JTextField jtPlayerText;
    private javax.swing.JTextField jtPlayerText2;
    private javax.swing.JTextField jtPlayerText3;
    private javax.swing.JButton playerContinueButton;
    private javax.swing.JTextField playerScore;
    // End of variables declaration//GEN-END:variables
}
